PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Images ( id INTEGER PRIMARY KEY, image_name varchar2(250) not null, alt_text varchar2(250));
CREATE TABLE Pages ( id INTEGER PRIMARY KEY, name varchar2(250) not null, url varchar2(250)not null, date_modified int ,images TEXT,JSON_data TEXT);
INSERT INTO "Pages" VALUES(1,'Blue Mountains','http://www.destinationnsw.com.au/smartphoneapps/blue-mountains',1360561051000,'','{"Page":{"Title":"Blue Mountains","Content":"\r\n<div id=\"content_div_175870\">\r\n\r\n<\/div>\r\n"},"Children":[{"Name":"Home","Url":"http:\/\/www.destinationnsw.com.au\/smartphoneapps\/blue-mountains\/home"},{"Name":"Home","Url":"http:\/\/www.destinationnsw.com.au\/smartphoneapps\/blue-mountains\/home2"},{"Name":"About Blue Mountains","Url":"http:\/\/www.destinationnsw.com.au\/smartphoneapps\/blue-mountains\/about-blue-mountains"},{"Name":"Things to do","Url":"http:\/\/www.destinationnsw.com.au\/smartphoneapps\/blue-mountains\/things-to-do"}]}');
INSERT INTO "Pages" VALUES(2,'Home','http://www.destinationnsw.com.au/smartphoneapps/blue-mountains/home',1360561052000,'','{"Page":{"Title":"Home","Content":"\r\n<div id=\"content_div_175879\">\r\nThe blue mountains is a great place to go for a relaxing weekend ..........................\r\n\r\n<\/div>\r\n"}}');
INSERT INTO "Pages" VALUES(3,'Home','http://www.destinationnsw.com.au/smartphoneapps/blue-mountains/home2',1360561053000,'','{"Page":{"Title":"Home","Content":"\r\n<div id=\"content_div_175884\">\r\n\r\n<\/div>\r\n"}}');
INSERT INTO "Pages" VALUES(4,'','http://www.destinationnsw.com.au/smartphoneapps/blue-mountains/about-blue-mountains',1360561054000,'','null');
INSERT INTO "Pages" VALUES(5,'Things to do','http://www.destinationnsw.com.au/smartphoneapps/blue-mountains/things-to-do',1360561055000,'','{"Page":{"Title":"Things to do","Content":"\r\n<div id=\"content_div_175893\">\r\nIf you are into bush walking and nature.........................\r\n\r\n<\/div>\r\n"}}');
COMMIT;
